def child_id_cols():
    return['PatientID']


def header_cols():
    return ['FileMetaInformationGroupLength',
            'FileMetaInformationVersion',
            'MediaStorageSOPClassUID',
            'MediaStorageSOPInstanceUID',
            'TransferSyntaxUID',
            'ImplementationClassUID',
            'SourceApplicationEntityTitle']


def main_cols():
    return[{'number': '00080005', 'name': 'Specific Character Set'},
           {'number': '00080008', 'name': 'Image Type'},
           {'number': '00080016', 'name': 'SOP Class UID'},
           {'number': '00080018', 'name': 'SOP Instance UID'},
           {'number': '00080020', 'name': 'Study Date'},
           {'number': '00080030', 'name': 'Study Time'},
           #    'AccessionNumber',
           #    'Modality',
           #    'Manufacturer',
           #    'InstitutionName',
           #    'InstitutionAddress',
           #    'ReferringPhysicianName',
           #    'StudyDescription',
           #    'PerformingPhysicianName',
           {'number': '00081140', 'name': 'Referenced Image Sequence'},
           #    'LossyImageCompression',
           #    'SourceImageSequence',
           #    'PrivateCreator',
           #    'PatientID',
           #    'KVP',
           #    'FrameTime',
           #    'Exposure',
           #    'RadiationSetting',
           #    'PositionerMotion',
           #    'PositionerPrimaryAngle',
           #    'Positioner Secondary Angle',
           #    '[Maximum Frame Size]',
           #    'StudyInstanceUID',
           #    'SeriesInstanceUID',
           #    'StudyID',
           #    'SeriesNumber',
           #    'InstanceNumber',
           #    'PatientOrientation',
           #    '[Image Sequence Number]',
           #    'SamplesperPixel',
           #    'PhotometricInterpretation',
           #    'NumberofFrames',
           #    'FrameIncrementPointer',
           #    'Rows',
           #    'Columns',
           #    'BitsAllocated',
           #    'BitsStored',
           #    'HighBit',
           #    'PixelRepresentation',
           #    'PixelIntensityRelationship',
           #    'RecommendedViewingMode',
           #    'RWavePointer',
           #    'MaskSubtractionSequence',
           #    'Privatetagdata',
           #    'CurveDimensions',
           #    'NumberofPoints',
           #    'TypeofData',
           #    'AxisUnits',
           #    'DataValueRepresentation',
           #    'MinimumCoordinateValue',
           #    'MaximumCoordinateValue',
           #    'CurveRange',
           #    'CurveDataDescriptor',
           #    'CoordinateStartValue',
           #    'CoordinateStepValue',
           #    'CurveData',
           #    'PixelData'
           ]


def patient_cols():
    return ['id',
            'PatientName',
            'PatientID',
            'PatientBirthDate',
            'PatientSex']
